name: camaras_seguridad
description: Videovigilancia

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 3.0.0

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  intl: ^0.18.0
  sqflite: ^2.3.0
  path_provider: ^2.0.15
  cupertino_icons: ^1.0.5
  fluttertoast: ^8.2.2
  flutter_easyloading: ^3.0.5
  flutter_mjpeg: ^2.0.4
  adaptive_theme: ^3.3.0
  shared_preferences: ^2.2.0
  #flutter_launcher_icons: ^0.13.1
  flutter_launcher_icons: ^0.10.0
  video_player: ^2.7.0

  gesture_zoom_box: ^0.0.4
  wid_mage: ^0.0.1
  image_gallery_saver: ^2.0.3
  flutter_speed_dial: ^7.0.0

  file: ^7.0.0
  image: ^3.0.2
  screen_recorder: ^0.2.0
  flutter_screen_recording: ^2.0.10
  gallery_saver: ^2.3.2
  ffmpeg_kit_flutter: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.2

flutter:

  uses-material-design: true



flutter_intl:
  main_locale: es_MX
  enabled: true
